### ISSUE TITLE
Should this be using CUDA/GPU out of the box?

### ISSUE THREAD

**Issue by ScyDev** [herval/deepdream-docker#3]
It doesn't seem to. No noticeable speed improvement against my other setup where I don't have a GPU.

**Comment by herval** [comment]
@ScyDev Accessing the GPU would require a specific setup on the host OS, specific drivers, etc - the goal here was to have an image you can simply download and run anywhere

If there's an easy way to do GPU access with no extra setup needed on the host OS, let me know and I'll implement here
