### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by fastrocket** [herval/deepdream-docker#8]
I'm getting this error when I try to run an image conversion on Windows 10:

RuntimeError: module compiled against API version 0xa but this version of numpy
is 0x9

The command I used on the Windows 10 host via gitbash is:

`$ winpty docker run -it -e INPUT=cat.jpg -e ITER=20 -e SCALE=0.10 -e MODEL='inception_3b/5x5_reduce' -v //g/dockerstuff/deepdream-docker-master:/data herval/deepdream`

The "//g/dockerstuff/.." is the notation for the g: drive (presumably from gitbash). I don't think it's the problem since the error is about numpy.

Any ideas?

**Comment by LeviBorodenko** [comment]
updating numpy will fix this issue.

**Comment by karalabe** [comment]
Add `pip install numpy --upgrade` after installing python + pip.

**Comment by rudolfwilliam** [comment]
I receive the same error message on OS X. Updating numpy did not fix the issue for me.

**Comment by fleshgordo** [comment]
I've updated numpy like this:

`docker run herval/deepdream pip install numpy --upgrade --ignore-installed`

but it indeed didn't fix the issue

**Comment by herval** [comment]
Fixed by @saracubillas
