### ISSUE TITLE
step by step correct install-PULL not build -t

### ISSUE THREAD

**Issue by AkoZ** [herval/deepdream-docker#9]
Ok for docker .. all done, find it there!: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/ and chose AMD instal for current CPU as intel too !! ...
then i dl your "herval" pre_install docker .. but the build doesn't go on ! ..
` docker build -t herval/deepdream
"docker build" requires exactly 1 argument.
See 'docker build --help'.
Usage:  docker build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile `

also i tried some trick as --> docker build -t Dockerfile/deepdream and define a sub-directory ...
MAY BE the solution is to open the file "Dockerfile" and just do all the instruction manually and not by any docker then to use docker ? (as in readme.md ..?)

1. So .. dockerfile seems like a script : how to make it install its lines ?

I know, many had found the way to get it ok .. i've installed all the packages before, and then i see your pre-build docker so i thought it would be easier .. but in fact the build in docker is not so direct.. some DEV easy secrets ;)
Regards for any stepBYstep & kind answer !

**Comment by AkoZ** [comment]
1 - is to be sure docker is started:
----> `sudo service docker start`
I"ve done `sudo docker` **pull** `herval/deepdream` 
PULL **instead of "build -t"** !! _and it begins to download_ some materials (coded as just 
`Using default tag: latest`
`latest: Pulling from herval/deepdream`
`6ffe5d2d6a97: Pull complete `
`f4e00f994fd4: Pull complete 
e99f3d1fc87b: Pull complete 
a3ed95caeb02: Pull complete `
also may be this is the trick ?
It has all completed `Status: Downloaded newer image for herval/deepdream:latest`
THEN ? for now to find back the next thing to do ?

________________________
OK gone on:
```
sudo docker run -i -t -e INPUT=img_start1.jpg -e ITER=20 -e SCALE=0.10 -e MODEL='inception_3b/5x5_reduce' -v /wheresMyimage/DeepD/tst/DOcker/deepdream-docker-master/imgs/img_start1.jpg:/data herval/deepdream
libdc1394 error: Failed to initialize libdc1394
Processing file: img_start1.jpg
Traceback (most recent call last):

File "deepdream.py", line 25, in <module>
    img = np.float32(PIL.Image.open('/data/%s' % input_file))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1996, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 20] Not a directory: '/data/img_start1.jpg'
```
MAY BE: i'll have to convert my .jpg to .png but i doubt this is the problem..
in fact as root i don't access /docker directory .. here is i suppose where the /data dir is ?
_**in fact i'd let img_start1.jgp at the end of the copied path !!!**_

**Comment by AkoZ** [comment]
hey some rules .. i think it's ok for now ! .. As i've found an error in my copied path in command... also the command ok is: ahem !!!! .. it hasn't stop the calculation ?? when does it stop ??
ok .. seems to continue an extra zoom .. then i've to change the dogs and birds collection with some painters styles ..
so: command done ok: 
`sudo docker run -i -t -e INPUT=myimage.jpg -e ITER=20 -e SCALE=0.10 -e MODEL='inception_3b/5x5_reduce' -v /home/user/somedirectories/DIR_where_i_put_myimage:/data herval/deepdream`

Thank you for all may it helps (as it's a bit what's written before, but with test and win ! ;)
Precisely: " Replace /path/to/your/folder to the folder where your INPUT file is" must be 
**re-written** "/path/to/your/folder"  by " /path/to/your/input_image_or_file_folder" (the folder where your INPUT file is).

**Comment by herval** [comment]
hah looks like you're good :-)
